config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  #devise_for :users, controllers: { registrations: 'users' }
  root 'reports#index'

  concern :commentable do
    resources :comments, only: [:destroy]
  end

  resources :reports, concerns: :commentable do
    member do
      get :copy_new
      post :comments
      post :good
    end
    collection do
      get :analysis
    end
  end

  resources :events
  resources :articles


  # concern :commentable do
  #   post 'toggle'
  # end
  # resources :posts, concerns: :commentable

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_comment.html.slim
h2 class="page-header"
  コメント
ul
  - unless @no_comments
    li コメントはありません。
  - else
    - target.comments.each do |comment|
      - if comment.id
        li class="media"
          h3 class="popover-title"
            = t(comment.created_at)
            = comment.user_name
            - if comment.user_id == current_user.id
              = link_to report_comment_path(target, comment), class: 'btn', method: :delete, data: { confirm: '削除しますか？' }
                i class="icon-white icon-trash"
                | 削除
          .popover-content
            = comment.content

  br

  - if @comment.errors.any?
    div id="error_explanation" class="alert alert-error"
      ul
        - @comment.errors.full_messages.each do |msg|
          li
            = msg

  = form_for([target, @comment], url: url) do |f|
    .field
      = f.text_area :content, { rows: "5", class: 'input-block-level ja_em'}
    .actions
      = f.submit 'コメントする', class: 'btn btn-success'