config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  #devise_for :users, controllers: { registrations: 'users' }
  root 'reports#index'

  concern :commentable do
    resources :comments, only: [:destroy]
  end

  resources :reports, concerns: :commentable do
    member do
      get :copy_new
      post :comments
      post :good
    end
    collection do
      get :analysis
    end
  end

  resources :events
  resources :articles


  # concern :commentable do
  #   post 'toggle'
  # end
  # resources :posts, concerns: :commentable

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  has_many :timereports, -> { order('id asc') }, dependent: :destroy
  has_many :comments, -> { order('id asc') }, as: :target
  has_many :good_counters, as: :target
  has_many :notices, as: :target
  accepts_nested_attributes_for :timereports, allow_destroy: true

  def copy
    report = self.class.new
    report.user_id = user_id
    timereport_size = self.timereports.size
    timereport_size.times do
      report.timereports.build()
    end
    report.attributes = self.attributes
    report.timereports.each_with_index do |new_timereport, n|
      new_timereport.attributes = self.timereports[n].attributes
    end
    report
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_report, only: [:show, :edit, :update, :copy_new, :destroy, :comments, :good]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @no_comments = @report.comments.any?
    if @no_comments
      @report.comments.order('created_at DESC')
    end
    @comment = @report.comments.build
  end

  # GET /reports/new
  def new
    @report = current_user.reports.new
    2.times do
      @report.timereports.build
    end
    @report.public = false
  end

  def copy_new
    @report = @report.copy
    @report.public = false
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_update_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def comments
    parameters = comment_params.merge(user_id: current_user.id)
    @comment = @report.comments.new(parameters)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to action: :show, notice: 'comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :show }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /reports/1/good
  def good
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:daily_date, :body, :public, :confidentiality, :rank, :user_id, timereports_attributes: [ :report_id, :time_from, :time_to, :occupation, :remark, :_destroy])
    end

    def report_update_params
      params.require(:report).permit(:daily_date, :body, :public, :confidentiality, :rank, :user_id, timereports_attributes: [ :id, :report_id, :time_from, :time_to, :occupation, :remark, :_destroy])
    end

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) +
    link_to("#", { onclick: "remove_fields(this)", class: "btn btn-danger" }) do
      raw(name)
    end
  end

  def link_to_add_fields(name, f, association, target)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to "#", { onclick: %Q[add_fields(this, "#{association}", "#{escape_javascript(fields)}", "#{target}")], class: "btn btn-info" } do
      raw(name)
    end
  end

  # 新規作成時、デフォルトの時刻を指定する
  def setting_default_time(i)
    case i
    when 0
      { h_start: 9, h_end: 12 }
    when 1
      { h_start: 13, h_end: 18 }
    else
      { h_start: 0, h_end: 0 }
    end
  end

  def occupation_table
    [
      ["プログラミング", "P"],
      ["テスト", "T"],
      ["レビュー", "R"],
      ["プログラム改修", "B"],
      ["ドキュメント", "C"],
      ["環境・支援", "E"],
      ["付帯サービス", "S"],
      ["営業・企画調査", "A"],
      ["管理・事務・他", "G"],
      ["会議・行事", "M"],
      ["教育・訓練", "L"],
      ["デザイン", "D"],
      ["出張(移動時間)", "F"]
    ]
  end
end

app/views/reports/_form.html.slim
= form_for @report do |f|
  - if @report.errors.any?
    #error_explanation
      h2 = "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      ul
        - @report.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :daily_date
    = f.date_field :daily_date
  .field
    table class="table table-bordered table-condensed header_style"
      thead
        tr
          th class="span4" 時刻
          th class="span3" 業務内容
          th class="span3" 備考
          th class="span1" 削除
      tbody id="timereports"
        = f.fields_for :timereports do |lf|
          = render partial: 'timereport_fields', locals: { f: lf}
        p
        = link_to_add_fields "<i class='icon-white icon-arrow-right'>行追加</i>", f, :timereports, "#timereports"
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :confidentiality
    = f.text_area :confidentiality
  .field
    = f.label :public
    = f.check_box :public
  .actions = f.submit

javascript:
  function remove_fields(link) {
    $(link).prev("input[type=hidden]").val("1");
    $(link).closest(".fields").hide();
  }

  function add_fields(link, association, content, target) {
    var new_id = new Date().getTime();
    var regexp = new RegExp("new_" + association, "g");
    $(target).append(content.replace(regexp, new_id));
  }

app/views/reports/_timereport_fields.html.slim
tr class="fields"
  - times = {}
  = f.hidden_field :id
  td class="span4"
    - times = setting_default_time(f.index)
    = f.time_select :time_from, {:time_separator => ':' ,:default => Time.now.change(hour: times[:h_start], min: 0), :minute_step => 5 }, {:class => "input-mini"}
    | ~
    = f.time_select :time_to, { time_separator: ':', default: Time.now.change(hour: times[:h_end], min: 0), minute_step: 5}, { class: "input-mini" }
  td class="span3"
    = f.select :occupation, occupation_table, { include_blank: true }, { class: "span12" }
  td class="span3"
    = f.text_area :remark, {:class => 'span12 ja_em'}
  td class="span1"
    - case f.index
    - when 0
    - else
      = link_to_remove_fields "削除<i class='icon-white icon-trash'></i>", f

app/views/reports/copy_new.html.slim
h1 Copy report

== render 'form'

= link_to 'Back', reports_path

app/views/reports/edit.html.slim
h1 Editing report

== render 'form'

= link_to 'Show', @report
'|
= link_to 'Back', reports_path

app/views/reports/index.html.slim
h1 Listing reports

table
  thead
    tr
      th Daily date
      th Public
      th Rank
      th User
      th
      th
      th

  tbody
    - @reports.each do |report|
      tr
        td = report.daily_date
        td = report.public
        td = report.rank
        td = report.user
        td = link_to 'Show', report
        td = link_to 'Copy', copy_new_report_path(report)
        td = link_to 'Edit', edit_report_path(report)
        td = link_to 'Destroy', report, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Report', new_report_path

app/views/reports/new.html.slim
h1 New report

== render 'form'

= link_to 'Back', reports_path

app/views/reports/show.html.slim
p
  strong Daily date:
  = @report.daily_date

table class="table table-bordered table-condensed header_style"
  tr
    th
      label 時刻
    th
      label 業務内容
    th
      label 進捗状況
    th
      label 備考
  - @report.timereports.each do | timereport |
    tr
      td
        = timereport.time_from.strftime("%H:%M")
        | 〜
        = timereport.time_to.strftime("%H:%M")
      td
        = table_show(timereport.occupation, occupation_table)
      td
        = timereport.remark

p
  strong Body:
  = @report.body
p
  strong Confidentiality:
  = @report.confidentiality
p
  strong Public:
  = @report.public


= render partial: '/shared/comment', locals: { target: @report, url: comments_report_path(report_id: @report.id) }


= link_to 'Edit', edit_report_path(@report)
'|
= link_to 'Back', reports_path